#!/bin/bash
# push_v6.sh — رفع تغييرات V6 إلى GitHub (OculusEgypt/ACIS)
set -e

BRANCH="feat/session-v6"
REPO_URL="https://OculusEgypt:${GITHUB_TOKEN}@github.com/OculusEgypt/ACIS.git"

echo "🚀 رفع V6 إلى GitHub..."
echo "الفرع: $BRANCH"

# إعداد git
git config user.email "acis-agent@replit.com" 2>/dev/null || true
git config user.name "ACIS Agent" 2>/dev/null || true

# إنشاء فرع V6
git checkout -B "$BRANCH"

# إضافة جميع التغييرات
git add -A

# commit
git commit -m "feat(v6): WebSocket Singleton + Billie Float + Performance fixes

### التغييرات الجوهرية:
- [T001] ws-singleton.ts — اتصال WS وحيد يمنع تعدد الاتصالات
- [T001] use-realtime.ts + use-ws-notifications.ts — معاد كتابتهما بالـ Singleton  
- [T001] notifications-panel.tsx — يستخدم WS Singleton
- [T001] QueryClient: refetchOnMount:false + refetchOnWindowFocus:false
- [T002] index.html — splash screen + dark CSS inline (حل الشاشة السوداء)
- [T003] /api/billie/web-search — DuckDuckGo + AI summary
- [T003] إصلاح text_fast → text_simple في billie.ts + nexus.ts
- [T004] billie-float.tsx — أيقونة بيليه العائمة من أي صفحة
- [T005] DEV_PLAN_V6.md — خطة التطوير الشاملة
- [T006] PROJECT_MEMORY.md — ذاكرة المشروع الدائمة
- layout.tsx v4.0 → v6.0

### تحسين الأداء:
- التنقل بين الصفحات فوري (refetchOnMount:false + staleTime:30s)
- اتصال WS واحد بدلاً من 3 اتصالات متوازية

🤖 Generated by ACIS Agent — $(date '+%Y-%m-%d %H:%M')" --no-verify

# رفع الفرع
git push "$REPO_URL" "$BRANCH" --force

echo ""
echo "✅ تم رفع الفرع: $BRANCH"
echo "🔗 https://github.com/OculusEgypt/ACIS/tree/$BRANCH"
